name: climatematch
channels:
 - conda-forge
 - nodefaults
dependencies:
 - adlfs
 - argopy
 - awscli
 - boto3
 - bottleneck
 - cartopy
 - cfgrib
 - ciso
 - climlab
 - dask-ml
 - datashader
 - descartes
 - earthaccess
 - eigen
 - eofs
 - erddapy
 - fastjmd95
 - flox
 - fsspec
 - gcm_filters
 - gcsfs
 - gh
 - geocube
 - geopandas
 - geopy
 - geoviews-core
 - git
 - git-lfs
 - gsw
 - h5netcdf
 - h5py
 - holoviews
 - hvplot
 - intake
 - intake-esm
 - intake-geopandas
 - intake-stac
 - intake-xarray
 - ipykernel>=6.21.2
 - ipyleaflet
 - ipytree
 - ipywidgets
 - jupyter-panel-proxy
 - jupyter-resource-usage
 - kerchunk
 - lxml
 - lz4
 - matplotlib-base
 - metpy
 - nb_conda_kernels
 - nbstripout
 - nc-time-axis
 - netcdf4
 - numcodecs
 - numpy
 - odc-stac
 - pandas
 - panel
 - parcels
 - param
 - pop-tools
 - pyarrow
 - pycamhd
 - pydap
 - pygeos
 - pystac
 - pystac-client
 - pythia-datasets
 - python-blosc
 - python-gist
 - python-graphviz
 - pyworld3 # needed for W2D3
 - rasterio
 - rechunker
 - rio-cogeo
 - rioxarray
 - s3fs
 - satpy
 - scikit-image
 - scikit-learn
 - scipy
 - seaborn
 - sparse
 - snakeviz
 - stackstac
 - tiledb-py
 - timezonefinder
 - xarray
 - xarrayutils
 - xarray-datatree
 - xarray_leaflet
 - xarray-spatial
 - xbatcher
# - xcape
 - xclim
 - esmf
 - xesmf
 - esmpy
 - xgcm
 - xhistogram
 - xmip
 - xmitgcm
 - xpublish
 - xrft
 - xskillscore
 - zarr
 - gh-scoped-creds
 - jupyterlab-git
 - pybind11 # needed for SDFC
 - texttable
 - openpyxl
 - pyworld3
 - wordcloud
 - nltk
 - ecco_v4_py
 - cmocean
 - ipykernel
 - boto3
 - pooch
 - eigen # needed for SDFC
 - pip
 - pip:
   - pyleoclim
   - afinn
   - "mystatsfunctions @ https://github.com/njleach/mystatsfunctions/archive/main.zip"
#   - "SDFC @ https://github.com/yrobink/SDFC/archive/master.zip" # this is not working
   -  https://github.com/mptouzel/PyDICE/archive/master.zip # for W2D3 Tutorial 2
 # Note: Enable after https://github.com/conda-incubator/conda-lock/pull/295
 # Uncomment and remove separate requirements.txt file
 #- pip:
 #  - jupyterlab-s3-browser>=0.12
