#!/usr/bin/env python
# coding: utf-8

# [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ClimateMatchAcademy/course-content/blob/main/tutorials/W1D3_RemoteSensingLandOceanandAtmosphere/instructor/W1D3_Tutorial5.ipynb)   <a href="https://kaggle.com/kernels/welcome?src=https://raw.githubusercontent.com/ClimateMatchAcademy/course-content/main/tutorials/W1D3_RemoteSensingLandOceanandAtmosphere/instructor/W1D3_Tutorial5.ipynb" target="_blank"><img alt="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"/></a>

# # **Tutorial 5: Calculating Anomalies Using Precipitation Data**
# 
# **Week 1, Day 3, Remote Sensing**
# 
# **Content creators:** Douglas Rao
# 
# **Content reviewers:** Katrina Dobson, Younkap Nina Duplex, Maria Gonzalez, Will Gregory, Nahid Hasan, Sherry Mi, Beatriz Cosenza Muralles, Jenna Pearson, Agustina Pesce, Chi Zhang, Ohad Zivan
# 
# **Content editors:** Jenna Pearson, Chi Zhang, Ohad Zivan
# 
# **Production editors:** Wesley Banfield, Jenna Pearson, Chi Zhang, Ohad Zivan
# 
# **Our 2023 Sponsors:** NASA TOPS

# # **Tutorial Objectives**
# 
# In this tutorial, you will learn how to calculate climate anomalies using satellite climate data records.
# 
# By the end of this tutorial you will be able to:
# 
# * Calculate an anomaly to a climatology.
# * Calculate the rolling mean of the anomaly data to smooth the time series and extract long-term signals/patterns.
# 

# # **Setup**

# In[ ]:


# !pip install s3fs --quiet

# properly install cartopy in colab to avoid session crash
# !apt-get install libproj-dev proj-data proj-bin --quiet
# !apt-get install libgeos-dev --quiet
# !pip install cython --quiet
# !pip install cartopy --quiet

# !apt-get -qq install python-cartopy python3-cartopy  --quiet
# !pip uninstall -y shapely  --quiet
# !pip install shapely --no-binary shapely  --quiet


# In[ ]:


# imports
import s3fs
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt
import cartopy
import cartopy.crs as ccrs
import boto3
import botocore
import pooch
import holoviews
from geoviews import Dataset as gvDataset
import geoviews.feature as gf
from geoviews import Image as gvImage


# ##  Video 1: Video 1 Name
# 

# ###  Video 1: Video 1 Name
# 

# In[ ]:


# @title Video 1: Video 1 Name
#Tech team will add code to format and display the video


# ##  Figure settings
# 

# ###  Figure settings
# 

# In[ ]:


# @title Figure settings
import ipywidgets as widgets       # interactive display
get_ipython().run_line_magic('config', "InlineBackend.figure_format = 'retina'")
plt.style.use("https://raw.githubusercontent.com/ClimateMatchAcademy/course-content/main/cma.mplstyle")


# # **Section 1: From Climatology to Anomaly**
# 
# Building upon your knowledge of climatology from the last tutorial, you will now calculate the anomalies from this climatology. An **anomaly**, in the context of climate studies, represents a departure from standard climatological conditions. For example, if the normal January temperature of the city that you live in is 10 °C and the January temperature of this year is 15 °C. We usually say the temperature anomaly of January this year is 5 °C above normal/ the climatology. The anomaly is an essential tool in detecting changes in climate patterns and is frequently utilized in critical climate reports such as those generated by the [Intergovernmental Panel on Climate Change (IPCC)](https://www.ipcc.ch/).
# 
# To calculate an anomaly, we first establish a reference period, usually a 30-year window, to define our climatology. In this process, it is crucial to use high-quality data and aggregate it to the desired spatial resolution and temporal frequency, such as weekly or monthly. The anomaly is then determined by subtracting this long-term average from a given observation, thus creating a useful metric for further climate analysis such as trend analysis.
# 
# In this tutorial, we will employ the [CPCP monthly precipitation Climate Data Record (CDR)](https://disc.gsfc.nasa.gov/datasets/GPCPMON_3.2/summary) to compute a monthly anomaly time series. Furthermore, we will learn to calculate the rolling mean of the generated precipitation anomaly time series. This knowledge will be invaluable for our upcoming tutorial on climate variability.

# ## **Section 1.1: Calculating the Monthly Anomaly**
# 
# To calculate anomaly, you first need to calculate the monthly climatology. Since you already learned how to do this during last tutorial, we will fast forward this step. 

# In[ ]:


# connect to the AWS S3 bucket for the GPCP Monthly Precipitation CDR data
fs = s3fs.S3FileSystem(anon=True)

# get the list of all data files in the AWS S3 bucket
file_pattern = 'noaa-cdr-precip-gpcp-monthly-pds/data/*/gpcp_v02r03_monthly_*.nc'
file_location = fs.glob(file_pattern)

# open connection to all data files
client = boto3.client('s3', config=botocore.client.Config(signature_version=botocore.UNSIGNED)) # initialize aws s3 bucket client
file_ob = [pooch.retrieve('http://s3.amazonaws.com/'+file,known_hash=None ) for file in file_location]

# open all the monthly data files and concatenate them along the time dimension
# this process will take ~ 1 minute to complete due to the number of data files
ds = xr.open_mfdataset(file_ob, combine='nested', concat_dim='time')
ds


# In[ ]:


# calculate climatology using `.sel()` and `.groupby()` directly.
precip_clim = ds.precip.sel(time=slice('1981-01-01', '2010-12-01')).groupby('time.month').mean(dim='time')
precip_clim


# Now we have the monthly precipitation climatology. How can we calculate the monthly anomaly?
# 
# As we learned before - let's use `.groupby()` from `xarray`. We can split the entire time period based on the month of the year and then subtract the climatology of that specific month from the monthly value and recombine the value together.

# In[ ]:


# use `.groupby()` to calculate the monthly anomaly
precip_anom = ds.precip.groupby('time.month') - precip_clim
precip_anom


# You may have noticed that there is an additional coordinate in the anomaly dataset. The additional coordinate is `month` which is a direct outcome because of the `.groupby()` action we just performed.
# 
# If you want to save the data for future use, you can write the data out to a netCDF file using `.to_netcdf()`. It will automatically carry all the coordinates, dimensions, and relevant information into the netCDF file.

# In[ ]:


# an example of how to export the GPCP monthly anomaly data comparing to the climatology period of 1981-2010.
# precip_anom.to_netcdf('t5_gpcp-monthly-anomaly_1981-2010.nc')


# ## **Section 1.2: Examining the Anomaly**
# 
# First, let's take a look at the geospatial pattern of the monthly anomaly of a selected month – January of 1979.

# In[ ]:


# initate plot
fig = plt.figure(figsize=(9,6))

# set map projection
ax = plt.axes(projection=ccrs.Robinson())

# add coastal lines to indicate land/ocean
ax.coastlines()

# add grid lines for latitude and longitude
ax.gridlines()

# add the precipitation data for
precip_anom.sel(time='1979-01-01').plot(ax=ax, transform=ccrs.PlateCarree(),
                                        vmin=-8, vmax=8, cmap='BrBG',
                                        cbar_kwargs=dict(shrink=0.5, label='Monthly Anomaly \n(mm/day)'))


# From the map of this monthly anomaly, we can see the spatial pattern of how precipitation for the January of 1979 has departed from the 30-year normal. Part of the Amazon saw notable increase of precipitation during this month as well as the northeast coast of the United States. 

# ### Interactive Demo 1.2
# 
# In the interactive demo below (make sure to run the code) you will be able to scroll through the anomaly for a few months in 1979 to see how it changes from month to month during this year.

# In[ ]:


holoviews.extension('bokeh')
dataset_plot = gvDataset(precip_anom.isel(time=slice(0,10))) # only the first 10, as it is a time consuming task
images = dataset_plot.to(gvImage, ['longitude', 'latitude'], ['precip'], 'time')
images.opts(cmap='BrBG', colorbar=True, width=600, height=400,projection=ccrs.Robinson(),
            clim=(-8,8),clabel ='Monthly Anomaly \n(mm/day)') * gf.coastline


# To visualize the changes in the precipitation anomaly over many months, we can also take a look at the time series of a selected grid. We will use the same point (0°N, 0°E) that we used as an example in the last tutorial.

# In[ ]:


# set up two subplots that share the x-axis to compare monthly precipitation and monthly anomaly
fig, axs = plt.subplots(2, sharex=True)
fig.suptitle('GPCP Monthly Precipitaion v.s. Monthly Anomaly')
axs[0].plot(ds.time, ds.precip.sel(latitude=0, longitude=0, method='nearest'))
axs[0].set_ylabel('Precip (mm/day)')
axs[1].plot(precip_anom.time, precip_anom.sel(latitude=0, longitude=0, method='nearest'))
axs[1].set_ylabel('Anomaly (mm/day)')
axs[1].set_xlabel('Time')

# add horizontal line of y=0 for the anomaly subplot
axs[1].axhline(y=0, color='k', linestyle='-')


# Note that, unlike the upper panel showing precipitation values, the lower panel displaying the monthly anomaly not exhibit distinct seasonal cycles. This discrepancy highlights one of the advantages of utilizing anomaly data for climate analysis. By removing the repetitive patterns induced by seasonality or other stable factors, we can effectively isolate the specific signals in the data that are of interest, such as climate variability or climate trends. This approach allows for a clearer focus on the desired climate-related patterns without the interference of predictable seasonal variations.

# # **Section 2: Anomaly Analysis**
# 
# In this section, we are going to explore a few different analyses on the anomaly data: 
# 
# - Calculating rolling mean
# - Calculating global mean
# 
# You have already practiced using these tools during the last two days or material, here we will focus on applying them to a much longer satellite data record than you have encountered previously.

# ## **Section 2.1: Rolling Mean**
# 
# The monthly anomaly time series often contains noisy data that may obscure the patterns associated with large-scale climate variability. To mitigate this noise and enhance the visibility of underlying patterns, we can apply a rolling mean technique using the `.rolling()` function. This approach involves smoothing the monthly time series to facilitate the identification of climate variability.

# In[ ]:


# calculate 12-month rolling mean for the selected location
grid_month = precip_anom.sel(latitude=0, longitude=0, method='nearest')
grid_rolling = grid_month.rolling(time=12, center=True).mean()


# In[ ]:


# create the time series plot of monthly anomaly
fig = plt.figure(figsize=(12,6))
grid_month.plot(label='Monthly Anomaly')
grid_rolling.plot(color='k', label='12-mon rolling mean')
plt.axhline(y=0, color='y', linestyle='-')
plt.ylabel('Precipitation Anomaly (mm/day)')
plt.legend()
plt.xlabel('Time')
# remove the automatically generated title
plt.title('')


# As you can see, the 12-month rolling mean removes the high-frequency variations of monthly precipitation anomaly data, allowing the slower-changing patterns of precipitation to become more apparent.

# ### Coding Exercises 2.1
# 
# 1. Calculate the 24-month rolling mean for the same grid and compare the three different time series (monthly anomaly, 12-month rolling mean, 24-month rolling mean).

# ```python
# # calculate 24-month rolling mean
# grid_rolling_24m = ...
# 
# # plot all three time series together with different colors
# fig = ...
# 
# ```

# In[ ]:


# to_remove solution

# calculate 24-month rolling mean
grid_rolling_24m = grid_month.rolling(time=24, center=True).mean()

# plot all three time series together with different colors
fig = plt.figure(figsize=(12,6))
grid_month.plot(label='Monthly anomaly')
grid_rolling.plot(color='k', label='12-mon rolling mean')
grid_rolling_24m.plot(color='r', label='24-mon rolling mean')
plt.axhline(y=0, color='y', linestyle='-')
plt.ylabel('Precipitation Anomaly (mm/day)')
plt.legend()
# remove the automatically generated title
plt.title('')


# ### Questions 2.1
# 
# 1. What are the major differences you notice between the 12 and 24 month rolling averages?
# 2. What would generally dictate the window size to use in a rolling average of a satellite derived climate variable such as precipitation anomalies?

# In[ ]:


# to_remove explanation

"""

1. The 24 month is smoother still, and in this case some of the 'bumps' rather than 'spiked' are removed.
2. The window size you use would largely depend on the time-scales of interest. For example, to calculate hydrological drought mostly caused by rainfall deficit you could use different windows ranging from 3 months to 60 months (https://climatedataguide.ucar.edu/climate-data/standardized-precipitation-index-spi). Averaging over a longer time period will remove smaller scale variability and allow you to focus on longer-term patterns which might be related to annual or decadal patterns (e.g., the Pacific Decadal Oscillation).

""";


# ## **Section 2.2: Global Mean**
# 
# When examining global-scale changes, it is common to aggregate global mean values from all grid cells. However, it is important to note that despite each grid having the same resolution of `2.5°×2.5°`, they represent different areas on the Earth's surface. Specifically, the same grid covers larger spatial areas in the tropics compared to the polar regions as discussed in the climate system overview day.
# 
# To address this issue, it is necessary to weight the values based on their respective surface areas. Unlink the model data you used previously, where you had the grid cell area available as a variable, for our gridded observations we will use weights based on the cosine of the latitude as this function takes into account the decreasing area towards the poles.

# In[ ]:


# calculate the weights using the latitude coordinates
weights = np.cos(np.deg2rad(precip_anom.latitude))
weights.name = "weights"
weights


# In[ ]:


# calculate weighted global monthly mean
anom_weighted = precip_anom.weighted(weights)
global_weighted_mean = anom_weighted.mean(('latitude', 'longitude'))
global_weighted_mean


# In[ ]:


# create the time series plot of global weighted monthly anomaly
fig = plt.figure(figsize=(12,6))
global_weighted_mean.plot(label='Monthly anomaly')
global_weighted_mean.rolling(time=12, center=True).mean(('latitude', 'longitude')).plot(color='k', label='12-mon rolling mean')
plt.axhline(y=0, color='y', linestyle='-')
plt.ylabel('Precipitation Anomaly (mm/day)')
plt.legend()


# ### Coding Exercises 2.2
# 
# 1. Plot the 12-month rolling average of the difference between the global weighted and unweighted mean time series.
# 

# ```python
# # calculate unweighted global mean
# global_unweighted_mean = ...
# 
# # calculate different between weighted and unweighted global mean
# global_diff = ...
# 
# # plot the time series of the difference
# fig = ...
# 
# ```

# In[ ]:


# to_remove solution

# calculate unweighted global mean
global_unweighted_mean = precip_anom.mean(('latitude', 'longitude'))

# calculate different between weighted and unweighted global mean
global_diff = global_weighted_mean - global_unweighted_mean

# plot the time series of the difference
fig = plt.figure(figsize=(12,6))
global_diff.rolling(time=12, center=True).mean(('latitude', 'longitude')).plot(color='k', label='12-mon rolling mean')
plt.axhline(y=0, color='y', linestyle='-')
plt.ylabel('Weighted Mean - Unweighted Mean')
plt.legend()


# ### Questions 2.2
# 
# 1. Give one example of why the weighted mean might be *higher* than the unweighted mean, as in the 2000-2004 period.

# In[ ]:


# to_remove explanation

"""

1. In the unweighted mean all the data contribute equally to the mean, but in the weighted mean the low-latitudes contribute most. One reason that the weighted mean could be higher than the unweighted mean would be if the equatorial region had higher anomalies than the poles. These would be counted less in the unweighted mean and more in the weighted mean.

""";


# # **Summary**
# 
# In this tutorial, you learned how to calculate a climate anomaly using satellite derived precipitation data. 
# 
# * The anomaly allows us to look at the signals that may be covered by the seasonal cycle pattern (e.g., temperature/precipitation seasonal cycle).
# * The anomaly data can be further smoothed using rolling mean to reveal longer-term signals at annual or decade time scale.
# 
# We will use the anomaly concept to study climate variability in the next tutorial.
# 

# # **Resources**

# Data from this tutorial can be accessed [here](https://noaa-cdr-precip-gpcp-monthly-pds.s3.amazonaws.com/index.html#data/).
