name: process-notebooks
description: 'Run processing of notebooks'
inputs:
  nbs:
    description: 'notebooks to execute'
    required: true
    type: string
  exec_flag:
    description: 'flag for execution'
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
        ref: ${{ github.head_ref }}
    
    - name: Setup
      uses: ./.github/actions/setup
      with:
        force_env_update: 'false'

    # - name: Install XKCD fonts
    #   run: |
    #     sudo apt-get update -yq
    #     sudo sh -c "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"
    #     sudo apt-get install msttcorefonts -qq
    #     rm -f $HOME/.matplotlib/fontList.cache

    - name: Process notebooks
      id: process_notebooks
      run: |
        python ci/process_notebooks.py ${{ inputs.nbs }} ${{ inputs.exec_flag}}
      shell: bash -l {0}

    - name: verify exercices
      continue-on-error: true
      id: verify_exercices
      run: |
        python ci/verify_exercises.py ${{ inputs.nbs }} --c "$COMMIT_MESSAGE"
      shell: bash -l {0}

    - name: make PR comment notebooks
      id: pr_comment
      run: |
        branch=${{ github.event.pull_request.head.ref }}
        python ci/make_pr_comment.py ${{ inputs.nbs }} --branch $branch --o comment.txt
      shell: bash -l {0}
