name: notebook-pr
on:
  workflow_dispatch:
  pull_request:
    branches: main
    paths:
      - '**/*.ipynb'
      - .github/workflows/notebook-pr.yaml
      - .github/actions/setup-ci.yaml
      - 'environment.yml'
      - '**/requirements.txt'

env:
  NB_KERNEL: python
  NMA_REPO: course-content
  NMA_MAIN_BRANCH: main

jobs:

  process-notebooks:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Get commit message
        run: |
          readonly local msg=$(git log -1 --pretty=format:"%s")
          echo "COMMIT_MESSAGE=$msg" >> $GITHUB_ENV
          ls /home/runner/work/course-content/course-content/.github/
          ls /home/runner/work/course-content/course-content/.github/actions

      - name: Get changed files
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci')"
        id: changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: " "

      - name: Run Notebooks
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci')"
        uses: ./.github/actions/check-notebooks
        with:
          nbs: 'tutorials/*/*.ipynb'
          exec_flag: '--check-execution'

