name: notebook-pr
on:
  workflow_dispatch:
  pull_request:
    branches: main
    paths:
      - '**/*.ipynb'
      - .github/workflows/notebook-pr.yaml
      - .github/actions/setup-ci.yaml
      - 'environment.yml'
      - '**/requirements.txt'

env:
  NB_KERNEL: python
  NMA_REPO: course-content
  NMA_MAIN_BRANCH: main

jobs:

  process-notebooks:

    runs-on: ubuntu-latest
    container:
      image: wesleyban/climatematch-notebook
    steps:
      - name: Setup
        uses: ./.github/actions/setup-ci.yaml

      - name: Get changed files
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci')"
        id: changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: " "

      - name: Process notebooks
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci')"
        id: process_notebooks
        run: |
          branch=${{ github.event.pull_request.head.ref }}
          nbs="tutorials/*/*.ipynb"
          python ci/process_notebooks.py $nbs
          python ci/verify_exercises.py $nbs --c "$COMMIT_MESSAGE"
          python ci/make_pr_comment.py $nbs --branch $branch --o comment.txt

      - name: Add PR comment
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci')"
        uses: machine-learning-apps/pr-comment@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: comment.txt

      - name: Update READMEs
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci')"
        run: python ci/generate_tutorial_readmes.py

      - name: Remove unreferenced derivatives
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci') && success()"
        run: |
          python ci/find_unreferenced_content.py > to_remove.txt
          if [ -s to_remove.txt ]; then git rm --pathspec-from-file=to_remove.txt; fi

      - name: Commit post-processed files
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci') && success()"
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add '**/*.ipynb'
          git add '**/static/*.png'
          git add '**/solutions/*.py'
          git add '**/README.md'
          git diff-index --quiet HEAD || git commit -m "Process tutorial notebooks"

      - name: Push post-processed files
        if: "!contains(env.COMMIT_MESSAGE, 'skip ci') && success()"
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
