name: Manual CI update

on:
  workflow_dispatch:

jobs:
  update-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Force Update environment
        uses: ./.github/actions/setup
        with:
          force_env_update: "true"
